language: java
jdk:
    - openjdk8
script: 
    - bash build --debug
    - bash travisafter.sh
# We need to avoid sudo for caching on Travis
# http://docs.travis-ci.com/user/caching/
sudo: false

addons:
    apt:
        packages:
            - curl
            - maven
            - build-essential
            - sed

cache:
   directories:
        - $HOME/.m2

before_script:
    - export MAVEN_SKIP_RC=true
    - export MAVEN_OPTS="-Xms1024m -Xmx2g -XX:MaxPermSize=512m"

